### ISSUE TITLE
[Discussion] SessionID vs Authentication per User

### ISSUE THREAD

**Issue by silvanheller** [dres-dev/DRES#113]
The current way a user authenticates themselves is via the SessionID which is not generated per user, but per browser session. This is not ideal for evaluation scenarios where not every user has direct access to the full system they are using. 

I would propose a scheme to authenticate submissions where there is a user-based authentication, so that the system can be set up in advance by an admin and not every participant has to manually check their sessionid and then somehow enter that in the system.

**Comment by lucaro** [comment]
The authentication based on a session id is deliberate, since it enables to distinguish between actions taken by different devices which might be using the same user account. Especially in a distributed setting, it is desirable to not only know which account but rather which session was the origin of a particular action.

**Comment by mpas97** [comment]
The sessionId could be something like a hash of the username+password, so it would become invalid as e.g. the password changes. As Silvan said, that way I could have set up all instances before the evaluation. But this way, we first have to wait until all users have connected to DRES, submitted me their session ids, so I can redeploy all vitrivr-ng instances with the changed config etc. So we'll need at least 20min in that evalution to become DRES ready.
Perhaps there should be a config option in future, so we can choose between multi device or a kind of static id. Because in my case I really don't need the ability to distinguish between actions taken by different devices, but to set up like 10 instances before and not during the meeting would be nice for all. For the admin as a lot of work can be done beforehand, it can even be tested, so no copy paste error has been made etc and all participants don't have to wait until all instances have been edited and redeployed.

**Comment by lucaro** [comment]
While I see your point, hashing some user data is certainly not the way to go here. What I could see as an option would be to have user-specific API keys which can be generated and revoked by an individual user for their account and for an admin for all accounts. This would solve the problem with ahead-of-time deployment but still not enable the distinction of individual devices. Supporting any more sophisticated authentication management would be a larger change and certainly not something that would happen any time soon. A substantially easier solution to this issue would be to add a configuration option to the UI of the systems wanting to interact with DRES, such that the session id can be set by an end-user (for example by just pasting it into an appropriate field in a settings panel), rather than having to edit configuration files. vitrivr-ng even used to support local versions of the configuration exactly for such cases, this functionality was however removed at some point, as far as I know.
