### ISSUE TITLE
Adjust Submission Responses

### ISSUE THREAD

**Issue by sauterl** [dres-dev/DRES#16]
Some of the submission responses do not have appropriate http codes:

- [x] Rejection is 500 (should be 208)
- [x] Replace 2xx with 4xx for frontend handling
- [x] Revisit response codes

**Comment by ppanopticon** [comment]
So I've had a look at this one:

1. There currently are a lot of things that can go wrong internally when posting a submission. These error conditions mostly result in an IllegalArgumentException or IllegalStateException because we're using Kotlin's _check()_ or _require()_ throughout the stack, which makes it hard to distinguish between the different causes. So a first step would be to introduce dedicated exceptions for things that can go wrong and can be caused by erroneous user input. 

2. Even though internally, we may be able to distinguish between many different error conditions, I would not make too many different distinctions on the API side. It simply complicates things without making them more correct or even clearer. For example, the 208 status we return for rejection of submissions is not really the right choice here, because this is a status code reserved for WebDAV. 

We could go for a 202 but then again, what would a client do with this information? Since there are many different submission filters, there are also many different things that can cause a rejection so no one is going to be able to act upon this special status.

I'd recommend the following types of errors:

- [ ] Submission processed -> 200
- [ ] Submission received but waiting to be judged -> 202
- [ ] Authorization / Authentication required -> 401, 403
- [ ] Run or competition unknown -> 404
- [ ] Bad request by the user -> 400 (missing or unknown collection, missing or unknown item, rejected by filter, bad timing etc.)
- [ ] Shit's gone horribly wrong, we failed to handle it and there is probably a burning dumpster fire somewhere -> 500

Any thoughts?

**Comment by lucaro** [comment]
I would still differentiate between a submission which was technically valid but filtered out from submissions which are invalid in any case. For rejected submissions, I'd suggest 412 'Precondition Failed'. Otherwise, I agree with your list.
