### ISSUE TITLE
Build automation

### ISSUE THREAD

**Issue by lucaro** [dres-dev/DRES#179]
- [ ] pipeline which automatically increases the version number after a merge into master
- [x] pipeline which builds master and publishes archive as release
- [x] pipeline which builds master and publishes docker image as release

**Comment by ppanopticon** [comment]
I've created a GitHub action which generates releases (Archive + Docker image) upon adding a version tag (v0.x) to a commit. 

This is a pattern I've had a very positive experience with over the past few months because it gives you control over when releases should be created. I wonder if we really need automation to the point that versions are increased automatically upon merging into master. Especially since the solutions I've seen so far did not really convince me.

**Comment by lucaro** [comment]
I don't really see the benefit of having a docker image, since we ship all dependencies with the sole exception of a JVM. But since it doesn't really cost us anything to offer one, sure, why not...

**Comment by ppanopticon** [comment]
Frankly, I was convinced that #179 requested a docker image just to then realize (after I did all the work) that this was not the case. So here it is... :-)
