### ISSUE TITLE
Performance Optimisation

### ISSUE THREAD

**Issue by sauterl** [dres-dev/DRES#267]
* Client side optimisation hunt: Reduce calls as best as possible
  - [x] Debounce state request upon submissions, every 0.5s could be reasonable
  - [x] Reduce ping (currently every second, could be every 10 seconds)
* Stresstest viewers and investigate where and why the clock doesn't properly update

**Comment by ppanopticon** [comment]
This has been implemented on dev. The way it work is that the timer (ever 1s) and the regular state updates to WebSocket messaging (random) are now debounced. Furthermore, if a state update is triggered by WebSocket that state is not explicitly queried again but reused instead. This should minimize overhead significantly when high load is generated due to a lot of submissions.

Needs extensive testing!

**Comment by lucaro** [comment]
Sounds good. Have you had a chance to test if the countdown now works properly even under a high submission load?

**Comment by ppanopticon** [comment]
It seems to be able to cope just fine with the load generated by your script.
