### ISSUE TITLE
Prevent hint-less tasks from being stored

### ISSUE THREAD

**Issue by sauterl** [dres-dev/DRES#269]
- [x] Actively prevent storing tasks without a query hint
- [x] ~~Add target as query hint for "Visual KIS" tasks~~

**Comment by ppanopticon** [comment]
I think the second part of this ticket lacks specification and is frankly ill-posed:

1. When should the target be added as query hint? Upon selection of the target item? When entering the start and end of the target? Both? What happens if the user specifies these out of order?
2. Can this pre-selection be overridden by a user? How should adjustments to the target be propagated to the query hint in this case (or shouldn't they)?
3. Given the generic nature of the form, do we really want to add specific business logic like this? 

Personally, I don't think that this is a good idea. I'd argue that if we really wanted to provide assistance for such specific use cases, we should probably design dedicated setup forms that do not offer the additional degree of freedom that causes the issue in the first place.

**Comment by lucaro** [comment]
I agree. The only somewhat sensible mechanism I could imagine is that, when specifying a hint but not a target and clicking on the save button, the target could be added before saving. Depending on how the first item in the list was implemented though, such functionality might be redundant.

**Comment by ppanopticon** [comment]
<img width="763" alt="screenshot" src="https://user-images.githubusercontent.com/2353196/126440812-10d3b151-cc56-4a4a-845e-44d0d059ad90.png">

This is how it is solved now! Obviously, the dialog refuses to save unless a query hint has been specified.

Frankly, I'm against any logic that is specific for a certain type of task. The approach you suggest only works for tasks where the query hint has the same type as the query target.

**Comment by lucaro** [comment]
I think this solution is perfectly adequate. The only potential criticism I'd have concerns the lack of contrast between the dark-red text on a gray background. 😉
