### ISSUE TITLE
[Bug] Task Viewer Lost Seconds at the Beginning

### ISSUE THREAD

**Issue by sauterl** [dres-dev/DRES#309]
Currently, the task viewer always misses the first few seconds of a query hint

**Comment by lucaro** [comment]
I fixed the jumping counter issue, but in some testing, the trigger for displaying the relevant hints did not always work reliably. @ppanopticon it would be great if you could have a look at this.

**Comment by ppanopticon** [comment]
I have (yet again) adjusted the entire thing: The backend is now fully responsible for time tracking and the frontend merely reacts to these changes.

It now seems to work. But please test it because the only task that I could really test it with is misconfigured... :-)

**Comment by lucaro** [comment]
Feel free to change that task to suit your needs 😜 
The only thing I'm wondering now is how this explicit elapsed timer plays together with the now explicit end timestamp for a task hint in cases a task duration is extended. I haven't had a chance to test this yet, but I expect that it would just now show any task hints anymore in case a task is extended. If this is indeed the case, it would probably not constitute intended behavior.

**Comment by ppanopticon** [comment]
Well since I don't have all the data (media files etc.) this is easier said than done since any new competition I might build will not start... we're just too thorough with all the checks.

I *believe* this should not be an issue as long as the final element has an "open" end, i.e., no fixed end timestamp. But we better test this. The question is, though, if we should leave the last element's end timestamp open by default or if we should fix it.

If it behaves as I expect, though, it would allow for neat things such as "extensions with visible hints" vs. "extensions without visible hints".

**Comment by lucaro** [comment]
Testing this should be trivial even without having the files since you can just use textual targets/hints only, which will not trigger any rendering. I agree that this should not be a problem when the end time of the last hint is left open. Didn't one of the last changes automatically fill in the end time on the UI side though?

**Comment by ppanopticon** [comment]
I see - I guess I should try this then.

Indeed yes! That's what I meant by the default behaviour of this new functionality.

**Comment by lucaro** [comment]
So we may not want to auto-fill the end time for the last element then. How about auto-filling the end time of the previously last element whenever a new one is added, so all including the second to last hints would show the end explicitly. Wouldn't this achieve the same effect?

**Comment by ppanopticon** [comment]
I can confirm that behaviour is as expected. 

I have adjusted the form builder as such that the last hint will always have and empty end-timestamp by default (i.e., open-ended display depending on task duration).

**Comment by lucaro** [comment]
The timing mechanism now appears to be working as intended. I, therefore, applied the appropriate label.
