### ISSUE TITLE
Investigate Xodus as replacement for MapDB

### ISSUE THREAD

**Issue by lucaro** [dres-dev/DRES#314]
Given that MapDB is not the most ideal storage solution for our purposes and Xodus is a much more actively developed project, it might be worth investigating what benefits could be had from migration and if they would be worth the effort.

**Comment by ppanopticon** [comment]
I did some research as to how this issue could be tackled and I can report that I expect this change to be a major undertaking if done right (which is not an argument against it, just to be clear). At a high level, I see two alternatives:

**Alternative 1**

- We use [Xodus (2.0.1) entity stores](https://github.com/JetBrains/xodus/wiki/Entity-Stores) to  store all required information.
- We use [Xodus DNQ](https://github.com/JetBrains/xodus-dnq) as an abstraction layer for the model.

Xodus DNQ is basically a mapper between the entity store and Kotlin classes (similar to an ORM) and provides a query and interaction layer for the underlying database.

*Impact:*
- All model classes must be adjusted so that they inherit from _XdEntity_. 
- Persistent data model will change because certain features are not supported directly (e.g. complex types, sealed classes etc.)
- All DAO classes will become obsolete since Xodus DNQ provides a (quite powerful) API.
- All API endpoints and controller classes that use the DAO classes must be adjusted.

* Simplification: **
To simplify the change, it would be possible to abstract Xodus DNQ functionality away into the existing DAOs. However, I would recommend against this since it creates a level of indirection that obfuscates the use of Xodus DNQ (especially when multiple entities are affected by an operation). Furthermore, there is still a need to adjust API endpoints and controllers due to Xodus' transaction semantic (and we cannot push this into the DAOs if we want transactionality for complex operation involving multiple entities).

** lternative 2:** 
- We only use [Xodus (2.0.1) entity stores](https://github.com/JetBrains/xodus/wiki/Entity-Stores) to store all required information.
- We then create some sort of binding between the existing entities and the persistent representation (similar to the Serializers).

*Impact:*
- Model classes can be left as-is but serialisation logic must be replaced. I'm not entirely sure yet, where a suitable entry point for this change would be.
- Due to Xodus transaction semantic we will still need changes to existing controllers (i.e. all API endpoints etc.) to support complex operations

While alternative 2 is probably the simpler change, notwithstanding fringe cases that blow everything up, I'd argue that alternative 1 is the cleaner solution and it provides some needed opportunity to perform some spring cleaning.

Any thoughts?

**Comment by ppanopticon** [comment]
I did some research as to how this issue could be tackled and I can report that I expect this change to be a major undertaking if done right (which is not an argument against it, just to be clear). At a high level, I see two alternatives:

**Alternative 1**

- We use [Xodus (2.0.1) entity stores](https://github.com/JetBrains/xodus/wiki/Entity-Stores) to  store all required information.
- We use [Xodus DNQ](https://github.com/JetBrains/xodus-dnq) as an abstraction layer for the model.

Xodus DNQ is basically a mapper between the entity store and Kotlin classes (similar to an ORM) and provides a query and interaction layer for the underlying database.

*Impact:*
- All model classes must be adjusted so that they inherit from _XdEntity_. 
- Persistent data model will change because certain features are not supported directly (e.g. complex types, sealed classes etc.)
- All DAO classes will become obsolete since Xodus DNQ provides a (quite powerful) API.
- All API endpoints and controller classes that use the DAO classes must be adjusted.

* Simplification: **
To simplify the change, it would be possible to abstract Xodus DNQ functionality away into the existing DAOs. However, I would recommend against this since it creates a level of indirection that obfuscates the use of Xodus DNQ (especially when multiple entities are affected by an operation). Furthermore, there is still a need to adjust API endpoints and controllers due to Xodus' transaction semantic (and we cannot push this into the DAOs if we want transactionality for complex operation involving multiple entities).

** lternative 2:** 
- We only use [Xodus (2.0.1) entity stores](https://github.com/JetBrains/xodus/wiki/Entity-Stores) to store all required information.
- We then create some sort of binding between the existing entities and the persistent representation (similar to the Serializers).

*Impact:*
- Model classes can be left as-is but serialisation logic must be replaced. I'm not entirely sure yet, where a suitable entry point for this change would be.
- Due to Xodus transaction semantic we will still need changes to existing controllers (i.e. all API endpoints etc.) to support complex operations

While alternative 2 is probably the simpler change, notwithstanding fringe cases that blow everything up, I'd argue that alternative 1 is the cleaner solution and it provides some needed opportunity to perform some spring cleaning.

Any thoughts?

**Comment by lucaro** [comment]
While I agree that the second alternative sounds like the smaller change, there might be some edge cases that are so tedious to handle that it doesn't make the tradeoff worth it. I don't have any experience with these specific technologies, so I couldn't tell, but it feels to me that alternative 1 would be the saver bet. At least then, everything would be consistent. Having had a brief look at the DQN examples, it looks to me like most changes to the API handlers would be grunt work rather than elaborate re-engineering, so at least it should be straight forward in many cases, even if it takes quite a bit of work to get there. It might still make sense to have an abstraction layer that offers a bunch of convenience functions, like commonly used query expressions. If the API of such a layer can he made to be similar to the current DAOs, it might even make the changes less invasive, at least in the cases where data is only read.

**Comment by sauterl** [comment]
Closing this issue since we did the major work of this already
