### ISSUE TITLE
Indicate when Evaluation would overwrite changes

### ISSUE THREAD

**Issue by lucaro** [dres-dev/DRES#382]
The evaluation should store a timestamp or hash of when it was last saved in order to identify during saving if other changes occurred in the meantime. The UI can then warn accordingly.

**Comment by ppanopticon** [comment]
I suppose that this issue is related to what we discussed on Monday (in which case the wording of the title is misleading).

Anyhow, I have added such a check to the `UpdateEvaluationTemplateHandler`. It now compares a `modified` timestamp to the one stored in the database. If they don't match, an update in rejected with a HTTP 409 error.

**Comment by lucaro** [comment]
Will the user get a pop-up in this case, or is the error just shown in the toast message, the same as the success message would be?

**Comment by ppanopticon** [comment]
It's a toast message as with all the other status indicators and errors.

**Comment by lucaro** [comment]
That's maybe something we'd want to change in the future, as users might overlook those easily.
