### ISSUE TITLE
Normalised competition scores are only updated upon task change

### ISSUE THREAD

**Issue by sauterl** [dres-dev/DRES#404]

**Comment by ppanopticon** [comment]
The `ScoreboardsUpdatable` is no longer 'stateful', i.e., I removed the `dirty` flag and instead, scoreboards are updated at a fixed interval (5 seconds). 

I see the following argument for this approach: The `dirty` flags intention is to prevent superfluous updates to save resources. However, at the time resources need to be saved (when a task is running), this flag will be true all the time anyway, because it needs to be triggered by every submission. The only time the flag is false is when resources are not an issue (in between tasks). So we might as well remove it.

**Comment by lucaro** [comment]
While I get the argument, from a user-experience point of view, this is a step in the wrong direction. The 5 second delay might be just long enough for people to be no longer able to associate their actions with the resulting changes. This is especially the case when there are several submissions in a sort time window. The update interval in the backend should be aligned with the update interval in the frontend in order to avoid inconsistent intermediate states.

**Comment by ppanopticon** [comment]
I have my doubts that users will notice. But of course we can reduce the timeout. 

In order to achieve what you want, however, we'll have to move to sub-second update interval. This then begs the question, why we don't just generate these scoreboards on the fly.

**Comment by lucaro** [comment]
We might as well do that. If that takes too long, we can still add a very short-term caching mechanism.

**Comment by sauterl** [comment]
Reopen this issue since it's still an issue

**Comment by ppanopticon** [comment]
This has been addressed by rewriting the ``Scorer`` and ``Scoreboard`` subsystem:
- Scorers are generally stateless and calculate scores on the fly upon invocation (with the exception of the CachingTaskScorer).
- All (stateful) Scoreboards and the CachingTaskScorer now have a 'dirty' flag that triggers re-calculation for the next invocation.
- Every time there is a change to _DbAnswerSet_, the Scorer of that task and all Scoreboards are marked as dirty. Here we use the ``TransientStoreSessionListener`` mechanism provided by Xodus DNQ.
- ``ScoreUpdateable`` and ``ScoreboardUpdateable`` have been removed.
