### ISSUE TITLE
Submission Handler acceptance test issues

### ISSUE THREAD

**Issue by sauterl** [dres-dev/DRES#420]
- [x] split transactions in legacy submission handler
- [x] split transactions in new submission handler
- [x] duplicate submission filtering does not work in new submission handler
- [x] answersets with multiple answers are not handled correctly in submission handler

**Comment by ppanopticon** [comment]
As briefly discussed in the telegram chat, I think we should rethink and re-redesign submission handling. I see two design goals are: 

1. Processing should be fast and efficient (main priority)
2. Flexibility should be retained
3. Clearer API 

Conceptually, I see the following approach:

- For transferring information about (past) submissions, we use the ``ApiSubmission`` class. This class encodes information, that is mainly used for display.
- For posting a new submission, we only use the ``ApiClientSubmission`` class without intermediate conversion to ``ApiSubmission``. This class holds all the information provided by the submitter and can be enriched with contextual information (e.g., userId) by the receiving endpoint.
- The ``RunManager::postSubmission()`` class processes, validates, transforms and persists enriched ``ApiClientSubmission`` instances.

The processing in ``RunManager::postSubmission`` should involve the following steps:
1. Sanity checks (basic checks that are particular to a ``RunManager`` instance).
2. Early filtering based on the information found in ``ApiClientSubmission``. This involves the ``TextualSubmissionFilter``, ``TemporalSubmissionFilter`` and ``ItemSubmissionFilter``. I would probably also put the ``SubmissionRateFilter``in this category, and change its current behaviour. One could also put ``MaximumTotalPerTeamFilter`` in this category, however, then a transaction is required.
3. (Start of write transaction)
4. Conversion to ``DbSubmission``. This conversion takes place using a canonical mapping.
5. Transformation of the ``DbSubmission``, e.g., ``MapToSegmentTransformer``. Since these simply transform an existing ``DbSubmission`` (change attributes, remove links etc.), we can actually do this "in-flight".
6. Validation
7. Saving

I'm not quite sure where to put ``CorrectPerTeamFilter``, `CorrectPerTeamItemFilter``, ``CorrectPerTeamMemberFilter``and ``MaximumWrongPerTeamFilter``. Because frankly, in the current version, they don't do anything useful because filtering precedes validation.

After successful processing, the ``ApiClientSubmission`` should be recorded in the audit trail. This is handled by the endpoint in a separate write-transaction. I would argue, that an audit log should be created, regardless of whether or not the submission has been persisted. But maybe, you do not agree with this.

Any thoughts?

**Comment by lucaro** [comment]
I generally agree. The behavior of the filters is the only real issue I see here, and also only from an optimization point of view. Do we maybe need to split the filter stages in two, and distinguish the filters that need a transaction and those that don't with an interface? Then again, when we want to persist all incoming submissions in the audit log, independent of whether they survive the entire chain, we need transactions for all of them anyway.

**Comment by ppanopticon** [comment]
I don't think the abstraction should be mainly around requiring a transaction or not. To be more efficient here, it might rather be sensible to "inline" some of these filters, e.g., the ``DuplicateSubmissionFilter``, since the current abstraction causes a certain overhead due to superfluous round-trips to the database. 

But more fundamentally, we currently we have to types of filters: 

1. Those that can be evaluated prior to validating a ``Submission`` (what I would actually call a filter).
2. Those that require prior validation (and thus, in the logic described before, the creation of a ``DbSubmission``)

From a system perspective, the first type of filter makes sense because they can help us prevent costly interactions with the database. The second type really isn't that interesting in that regard. So the question is, is there a particular use-case for these filters? 

Or in other words: What is the benefit of being able to place an arbitrary limit on the number of correct / incorrect submissions? It's not performance, since we need to do all the checks anyway in order to enforce the filter criterion.

The only real user-case I see in this regard, is to check if there has been a correct submission for a team and if so, to reject all subsequent submissions. For this, we don't need to validate the arriving submission. Instead, it's sufficient to examine the current state.

**Comment by lucaro** [comment]
Performance was never the motivation behind the filters; validity and task semantics were. The benefit of being able to reject submissions based on (the number of) previous submissions is that it enables you to define tasks that have certain semantics, e.g., 'you only get one try' or 'you are done after one correct submission'.

**Comment by ppanopticon** [comment]
To what end? This could simply be a scoring issue.

Besides, those examples you're giving are binary decisions based on the state of the evaluation only. They do not require examination of the incoming submission. In contrast, being able to specify an evaluation that allows for "at most five correct and ten incorrect submissions." seems a rather theoretical task scenario that, however, requires very real processing.

**Comment by lucaro** [comment]
One could also handle this on the scoring side, this would come with two disadvantages I can see:

1. it would substantially increase the complexity / diversity of the scoring functions, as they so far do not consider any such things.
2. it would make feedback to participants less direct since additional submissions that are not scored would not be rendered as such.

**Comment by lucaro** [comment]
The filters only ever make a binary decision per submission, that is dependent on the submission and the state of the task. So far, we only ever had filters that depend _either_ on the submission _or_ the state of the task, with the notable exception of the duplicate submission filter. Since we need that one in any case, I'm not sure if the mechanism can be fundamentally simplified.

**Comment by ppanopticon** [comment]
The duplicate submission filter is indeed an edge-case and I would argue for handling it as such, since we wish for efficient processing here. For the rest, I see two options:

- If we drop all submission filters that require prior validation (namely, ``MaximumWrongPerTeamFilter``, ``CorrectPerTeamMemberFilter``, ``CorrectPerTeamItemFilter`` and  ``CorrectPerTeamFilter``) , we can treat filtering as a single step taking place before persisting a submission in a read-only transaction. The edge-case you mentioned before, can be handled by a new implementation that rejects all submission for a team, if that team already has a correct submission (``OneCorrectPerTeamFilter``)
- If we need submission filters that require prior validation, then we need two filter steps one before and one after validation.

**Comment by lucaro** [comment]
The filters you listed can still be had without depending on validation. If `OneCorrectPerTeamFilter` is doable, which only needs to check if there is already a correct submission, we can do a `TwelveCorrectPerTeamFilter` or a `SeventeenTotalSubmissionsPerTeamFilter` without depending on the actual submission either. I don't see the issue, am I missing something?

**Comment by ppanopticon** [comment]
Well it indeed depends on what the semantics are:
- We can do ``MaximumTotalPerTeamFilter`` (never said we couldn't).
- We can do ``MaximumCorrectPerTeamFilter``, if we assume that submitting something wrong is no longer an option either after having reached the configured limit.
- Not sure if we can do ``MaximumWrongPerTeamFilter``, because the incoming submission might be correct, hence, validation is needed. Unless the semantic here is "Once you've made X mistakes, you're out.").
- Not sure if we can do ``CorrectPerTeamItemFilter``, because frankly, I have no idea what this is supposed to do.

**Comment by lucaro** [comment]
I agree entirely with the first two points. I also agree with point 3 and would argue, "Once you've made X mistakes, you're out." is a more sensible semantic than something like "Once you made X mistakes, any further mistakes will be ignored, but correct submissions will still be counted". The point for the `CorrectPerTeamItemFilter` was that in an AVS-like scenario was something along the lines of "if you already submitted X segments from the same video already and got points for them, we will not accept any more submissions with segments from that video". Even that could be done without validation, but since it was never used, we might as well remove it.

**Comment by ppanopticon** [comment]
So I have committed the change. I ran some basic tests using our test evaluation and it seems to work in the cases I tested.

I put also emphasis on the two issues mentioned in the ticket and have the following comments:

- The DuplicationSubmissionFilter de-duplicates submission based on the answer set, i.e., if a new submissions contains at least one answer set that is structurally identical to a recorded answer set for that task and team (i.e., all answers have been seen in this combination before), the entire submission is rejected. I'm a bit unsure, though, if this is what we intend.
- Having a single submission with multiple answer sets (e.g., one incorrect, one correct) is handled by the logic as though there were two submissions having the same timestamp each containing one answer set. Again, I'm not sure if this is how we intended this. 
- Having a submission with one answer set and multiple answers only counts as correct if the first item is correct. If we want a different behaviour here, then we need to change the corresponding validation logic, which only considers the first answer.

There are some very peculiar edge cases here, which are structurally. For example, we can have a single ``Submission`` with multiple answer sets, which will all individually be counted as a single answer to the task.  This way, we can circumvent all the ``MaximumXYSubmissionFilters ``, since they check on a ``Submission`` and not on an ``AnswerSet`` basis.

**Comment by lucaro** [comment]
Great! Regarding your points:

1. I'm not sure. It certainly sounds reasonable for now. I guess we can revisit this once there are active use cases for it.
2. Makes complete sense to me
3. I can imagine one would want to have more control over this, but it should be easy to just add more validators with different behavior once we need them.

To avoid being able to circumvent a submission number filter, we can always introduce a submission transformer that only keeps the first answer set in case we need something like this.
